//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMPMS.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TM.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this agency area, it is being used for properties.
        /// </summary>
        public static string AgencyAreaIsBeingUsed {
            get {
                return ResourceManager.GetString("AgencyAreaIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disclosure invitation has already sent to all owner parties.
        /// </summary>
        public static string AllDisclosureInvitationAreAlreadySent {
            get {
                return ResourceManager.GetString("AllDisclosureInvitationAreAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Property can only have 1 Board of the same Type linked to a Vacancy.
        /// </summary>
        public static string APropertyCanOnlyHave1Board {
            get {
                return ResourceManager.GetString("APropertyCanOnlyHave1Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign Property Manager to the Property.
        /// </summary>
        public static string AssignPropertyManagerToTheProperty {
            get {
                return ResourceManager.GetString("AssignPropertyManagerToTheProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign Sales Person to the Property.
        /// </summary>
        public static string AssignSalesPersonToTheProperty {
            get {
                return ResourceManager.GetString("AssignSalesPersonToTheProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this attribute, it is being used for properties.
        /// </summary>
        public static string AttributeIsBeingUsed {
            get {
                return ResourceManager.GetString("AttributeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this attribute, it is being used for questions.
        /// </summary>
        public static string AttributeIsBeingUsedForQuestion {
            get {
                return ResourceManager.GetString("AttributeIsBeingUsedForQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already another Authority with the same date range.
        /// </summary>
        public static string AuthorityDateOverlapped {
            get {
                return ResourceManager.GetString("AuthorityDateOverlapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authority is sent to owner, can not edit this authority.
        /// </summary>
        public static string AuthorityIsSentToOwnerSoCanNotEdit {
            get {
                return ResourceManager.GetString("AuthorityIsSentToOwnerSoCanNotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an existing Authority that has not been completed with dates that overlap this Authority..
        /// </summary>
        public static string AuthorityNotCompletedDateOverlapped {
            get {
                return ResourceManager.GetString("AuthorityNotCompletedDateOverlapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this authority type, it is being used for authorities.
        /// </summary>
        public static string AuthorityTypeIsBeingUsed {
            get {
                return ResourceManager.GetString("AuthorityTypeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this call type, it is being used for communication.
        /// </summary>
        public static string CallTypeIsBeingUsed {
            get {
                return ResourceManager.GetString("CallTypeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete &quot;Closed&quot; status type..
        /// </summary>
        public static string CannotDeleteClosedStatus {
            get {
                return ResourceManager.GetString("CannotDeleteClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this {0}, it&apos;s linked to the {1}.
        /// </summary>
        public static string CanNotDeleteItLinked {
            get {
                return ResourceManager.GetString("CanNotDeleteItLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete logged user!.
        /// </summary>
        public static string CanNotDeleteLoggedUser {
            get {
                return ResourceManager.GetString("CanNotDeleteLoggedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this owner, having {0} party(ies) in this owner!.
        /// </summary>
        public static string CanNotDeleteOwnerParty {
            get {
                return ResourceManager.GetString("CanNotDeleteOwnerParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this owner, having {0} property(s) in this owner!.
        /// </summary>
        public static string CanNotDeleteOwnerProperty {
            get {
                return ResourceManager.GetString("CanNotDeleteOwnerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the authority, it&apos;s the current authority of the property.
        /// </summary>
        public static string CannotDeleteTheAuthority {
            get {
                return ResourceManager.GetString("CannotDeleteTheAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the lease, it&apos;s the current lease of the property.
        /// </summary>
        public static string CannotDeleteTheLease {
            get {
                return ResourceManager.GetString("CannotDeleteTheLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the authority, it&apos;s signed.
        /// </summary>
        public static string CannotRemoveTheAuthorityBecauseItsSigned {
            get {
                return ResourceManager.GetString("CannotRemoveTheAuthorityBecauseItsSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the lease, it&apos;s signed.
        /// </summary>
        public static string CannotRemoveTheLeaseBecauseItsSigned {
            get {
                return ResourceManager.GetString("CannotRemoveTheLeaseBecauseItsSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this communication, it is being used for work orders.
        /// </summary>
        public static string CommIsBeingUsedForWorkOrder {
            get {
                return ResourceManager.GetString("CommIsBeingUsedForWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this commission type, it is being used for employee commissions.
        /// </summary>
        public static string CommissionTypeIsBeingUsed {
            get {
                return ResourceManager.GetString("CommissionTypeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this item, it is being used for communication item.
        /// </summary>
        public static string CommunicationItemIsBeingUsed {
            get {
                return ResourceManager.GetString("CommunicationItemIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this ref communication item type, it is being used for communication item/ref communication item.
        /// </summary>
        public static string CommunicationItemTypeIsBeingUsed {
            get {
                return ResourceManager.GetString("CommunicationItemTypeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this communication type, it is being used for agency.
        /// </summary>
        public static string CommunicationTypeIsBeingUsedInAgency {
            get {
                return ResourceManager.GetString("CommunicationTypeIsBeingUsedInAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this communication type, it is being used for communication header.
        /// </summary>
        public static string CommunicationTypeIsBeingUsedInCommunicationHeader {
            get {
                return ResourceManager.GetString("CommunicationTypeIsBeingUsedInCommunicationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this competitor because it is being used for properties.
        /// </summary>
        public static string CompetitorIsBeingUsed {
            get {
                return ResourceManager.GetString("CompetitorIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this compliance category, it is being used for properties compliance categories.
        /// </summary>
        public static string ComplianceCategoryIsBeingUsed {
            get {
                return ResourceManager.GetString("ComplianceCategoryIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this creditor, it is being used for properties compliance inspections.
        /// </summary>
        public static string CreditorIsBeingUsed {
            get {
                return ResourceManager.GetString("CreditorIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Disclosure Questionnaire has not been set up for this Property Type.
        /// </summary>
        public static string DisclosureSMSMissing {
            get {
                return ResourceManager.GetString("DisclosureSMSMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered. Please try another.
        /// </summary>
        public static string EmailIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is existing in the system.
        /// </summary>
        public static string EmailIsExistingInSystem {
            get {
                return ResourceManager.GetString("EmailIsExistingInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already belongs to another {0}.
        /// </summary>
        public static string EmailIsUsed {
            get {
                return ResourceManager.GetString("EmailIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this employee because it is being used for properties.
        /// </summary>
        public static string EmployeeIsBeingUsed {
            get {
                return ResourceManager.GetString("EmployeeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this employee because it is being used for commission.
        /// </summary>
        public static string EmployeeIsBeingUsedCommission {
            get {
                return ResourceManager.GetString("EmployeeIsBeingUsedCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End date need to less than Start date.
        /// </summary>
        public static string EndDateLessThanStartDate {
            get {
                return ResourceManager.GetString("EndDateLessThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete the status, it is being used for event status.
        /// </summary>
        public static string EventStatusIsBeingUsed {
            get {
                return ResourceManager.GetString("EventStatusIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expiry date cannot be smaller than start date.
        /// </summary>
        public static string ExpiryDateCannotBeSmallerThanStartDate {
            get {
                return ResourceManager.GetString("ExpiryDateCannotBeSmallerThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this fixed asset, it is being used for properties.
        /// </summary>
        public static string FixedAssetIsBeingUsed {
            get {
                return ResourceManager.GetString("FixedAssetIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already another Holiday with the same date range.
        /// </summary>
        public static string HolidayDateOverlapped {
            get {
                return ResourceManager.GetString("HolidayDateOverlapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email/password. Please try again..
        /// </summary>
        public static string IncorrectCredential {
            get {
                return ResourceManager.GetString("IncorrectCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already another Lease with the same date range.
        /// </summary>
        public static string LeaseDateOverlapped {
            get {
                return ResourceManager.GetString("LeaseDateOverlapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an existing Lease that has not been completed with dates that overlap this Lease..
        /// </summary>
        public static string LeaseNotCompletedDateOverlapped {
            get {
                return ResourceManager.GetString("LeaseNotCompletedDateOverlapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already another Lease with the same date range and tenant.
        /// </summary>
        public static string LeaseTenantDateOverlapped {
            get {
                return ResourceManager.GetString("LeaseTenantDateOverlapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this lease type, it is being used for leases.
        /// </summary>
        public static string LeaseTypeIsBeingUsed {
            get {
                return ResourceManager.GetString("LeaseTypeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to signature the authority.
        /// </summary>
        public static string NoPermissionToSignatureAuthority {
            get {
                return ResourceManager.GetString("NoPermissionToSignatureAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to signature the contract.
        /// </summary>
        public static string NoPermissionToSignatureContract {
            get {
                return ResourceManager.GetString("NoPermissionToSignatureContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to signature the lease.
        /// </summary>
        public static string NoPermissionToSignatureLease {
            get {
                return ResourceManager.GetString("NoPermissionToSignatureLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to update the lease.
        /// </summary>
        public static string NoPermissionToUpdateLease {
            get {
                return ResourceManager.GetString("NoPermissionToUpdateLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to update the property.
        /// </summary>
        public static string NoPermissionToUpdateProperty {
            get {
                return ResourceManager.GetString("NoPermissionToUpdateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only System Administrator can create new employee!.
        /// </summary>
        public static string OnlySystemAdministratorCanCreateNewEmployee {
            get {
                return ResourceManager.GetString("OnlySystemAdministratorCanCreateNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this owner, it is being used for communication header.
        /// </summary>
        public static string OwnerIsBeingUsedForCommHeader {
            get {
                return ResourceManager.GetString("OwnerIsBeingUsedForCommHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this owner, it is being used for property owners.
        /// </summary>
        public static string OwnerIsBeingUsedForPropertyOwner {
            get {
                return ResourceManager.GetString("OwnerIsBeingUsedForPropertyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Landlord disclosure cannot be sent as the Owner has no Mobile Phone recorded..
        /// </summary>
        public static string OwnerMobileRequired {
            get {
                return ResourceManager.GetString("OwnerMobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect..
        /// </summary>
        public static string PasswordIsIncorrect {
            get {
                return ResourceManager.GetString("PasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one contact for this owner before sending email again..
        /// </summary>
        public static string PleaseAddAtLeastOneContactForThisOwnerBeforeSendingEmailAgain {
            get {
                return ResourceManager.GetString("PleaseAddAtLeastOneContactForThisOwnerBeforeSendingEmailAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one owner party.
        /// </summary>
        public static string PleaseAddAtLeastOneOwnerParty {
            get {
                return ResourceManager.GetString("PleaseAddAtLeastOneOwnerParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one property type for this type.
        /// </summary>
        public static string PleaseAddAtLeastOnePropertyTypeForThisType {
            get {
                return ResourceManager.GetString("PleaseAddAtLeastOnePropertyTypeForThisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define the Email Body for {0} via Setup.
        /// </summary>
        public static string PleaseDefineTheEmailBody {
            get {
                return ResourceManager.GetString("PleaseDefineTheEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the {0}.
        /// </summary>
        public static string PleaseInput {
            get {
                return ResourceManager.GetString("PleaseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the {0}.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the lease type.
        /// </summary>
        public static string PleaseSelectTheLeaseType {
            get {
                return ResourceManager.GetString("PleaseSelectTheLeaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this power source, it is being used for fixed asset.
        /// </summary>
        public static string PowerSourceIsBeingUsed {
            get {
                return ResourceManager.GetString("PowerSourceIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this property owner, it is being used for current owner.
        /// </summary>
        public static string PropertyCurrentOwnerIsBeingUsed {
            get {
                return ResourceManager.GetString("PropertyCurrentOwnerIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the Owner details before creating {0}.
        /// </summary>
        public static string PropertyCurrentOwnerRequired {
            get {
                return ResourceManager.GetString("PropertyCurrentOwnerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this property group, it is being used for property.
        /// </summary>
        public static string PropertyGroupIsBeingUsed {
            get {
                return ResourceManager.GetString("PropertyGroupIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this property because it is being used for lease or authority.
        /// </summary>
        public static string PropertyIsBeingUsed {
            get {
                return ResourceManager.GetString("PropertyIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this property because it is being used for communication.
        /// </summary>
        public static string PropertyIsBeingUsedCommHeader {
            get {
                return ResourceManager.GetString("PropertyIsBeingUsedCommHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this property because it is being used for commission.
        /// </summary>
        public static string PropertyIsBeingUsedCommission {
            get {
                return ResourceManager.GetString("PropertyIsBeingUsedCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this property because it is being used for property owners.
        /// </summary>
        public static string PropertyIsBeingUsedForPropertyOwner {
            get {
                return ResourceManager.GetString("PropertyIsBeingUsedForPropertyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this property owner, it is being used for authorities.
        /// </summary>
        public static string PropertyOwnerIsBeingUsed {
            get {
                return ResourceManager.GetString("PropertyOwnerIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete the status, it is being used for properties.
        /// </summary>
        public static string PropertyStatusIsBeingUsed {
            get {
                return ResourceManager.GetString("PropertyStatusIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete the status, it is being used for agency.
        /// </summary>
        public static string PropertyStatusIsBeingUsedForAgency {
            get {
                return ResourceManager.GetString("PropertyStatusIsBeingUsedForAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete the status, it is being used for authorities.
        /// </summary>
        public static string PropertyStatusIsBeingUsedForAuthority {
            get {
                return ResourceManager.GetString("PropertyStatusIsBeingUsedForAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete the status, it is being used for leases.
        /// </summary>
        public static string PropertyStatusIsBeingUsedForLease {
            get {
                return ResourceManager.GetString("PropertyStatusIsBeingUsedForLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this property type, it is being used for properties.
        /// </summary>
        public static string PropertyTypeIsBeingUsed {
            get {
                return ResourceManager.GetString("PropertyTypeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this reason because it is being used for properties.
        /// </summary>
        public static string ReasonIsBeingUsed {
            get {
                return ResourceManager.GetString("ReasonIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} already exists, please try another.
        /// </summary>
        public static string RecordAlreadyExistsPleaseTryAnother {
            get {
                return ResourceManager.GetString("RecordAlreadyExistsPleaseTryAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this referral source, it is being used for properties.
        /// </summary>
        public static string ReferralSourceIsBeingUsed {
            get {
                return ResourceManager.GetString("ReferralSourceIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this rent type, it is being used for lease rent term.
        /// </summary>
        public static string RentTypeIsBeingUsed {
            get {
                return ResourceManager.GetString("RentTypeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set up the {0} in Agency Setup before continuing.
        /// </summary>
        public static string RequireAgencySetup {
            get {
                return ResourceManager.GetString("RequireAgencySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this urgency, it is being used for communication item/ ref communication item type.
        /// </summary>
        public static string ResponsibilityIsBeingUsed {
            get {
                return ResourceManager.GetString("ResponsibilityIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not send emails due to missing owner/email subject/email body on the selected rent reviews.
        /// </summary>
        public static string SendRentReviewFailed {
            get {
                return ResourceManager.GetString("SendRentReviewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this special condition, it is being used for property or lease.
        /// </summary>
        public static string SpecialConditionIsBeingUsed {
            get {
                return ResourceManager.GetString("SpecialConditionIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete the status, it is being used for {0}..
        /// </summary>
        public static string StatusInUse {
            get {
                return ResourceManager.GetString("StatusInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this task type, it is being used for employee.
        /// </summary>
        public static string TaskTypeIsBeingUsed {
            get {
                return ResourceManager.GetString("TaskTypeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this tenant because it is being used for leases.
        /// </summary>
        public static string TenantIsBeingUsed {
            get {
                return ResourceManager.GetString("TenantIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this tenant, it is being used for communication header.
        /// </summary>
        public static string TenantIsBeingUsedForCommHeader {
            get {
                return ResourceManager.GetString("TenantIsBeingUsedForCommHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute is already added. Please try another.
        /// </summary>
        public static string TheAttributeAlreadyAdded {
            get {
                return ResourceManager.GetString("TheAttributeAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not registered an account yet.
        /// </summary>
        public static string TheEmailIsNotRegisteredAnAccountYet {
            get {
                return ResourceManager.GetString("TheEmailIsNotRegisteredAnAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fixed asset is already added. Please try another.
        /// </summary>
        public static string TheFixedAssetAlreadyAdded {
            get {
                return ResourceManager.GetString("TheFixedAssetAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lease already current lease for authority.
        /// </summary>
        public static string TheLeaseAlreadyCurrentLeaseForAuthority {
            get {
                return ResourceManager.GetString("TheLeaseAlreadyCurrentLeaseForAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this questionnaire, it is being used for compliance.
        /// </summary>
        public static string TheQuestionnaireIsBeingUsedForComplaince {
            get {
                return ResourceManager.GetString("TheQuestionnaireIsBeingUsedForComplaince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this trade, it is being used for authorities maintenance or creditor.
        /// </summary>
        public static string TradeIsBeingUsed {
            get {
                return ResourceManager.GetString("TradeIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this urgency, it is being used for ref communication items.
        /// </summary>
        public static string UrgencyIsBeingUsed {
            get {
                return ResourceManager.GetString("UrgencyIsBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this user, it is being used for communication header.
        /// </summary>
        public static string UserIsBeingUsedForCommHeader {
            get {
                return ResourceManager.GetString("UserIsBeingUsedForCommHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to accept the lease offer first.
        /// </summary>
        public static string YouNeedToAcceptTheLeaseOfferFirst {
            get {
                return ResourceManager.GetString("YouNeedToAcceptTheLeaseOfferFirst", resourceCulture);
            }
        }
    }
}
